"""Script containing validation logic. It checks the processed data from the pipeline against expected structural and boundary conditions."""

from typing import List, Dict

def validate_pipeline(processed_data: List[Dict]) -> None:
    """
    Validates the output of the content moderation pipeline.
    Asserts the structural integrity and required boundary conditions 
    (PASS and BLOCK statuses) of the processed data.

    Args:
        processed_data: The list of dictionaries generated by processor.py.

    Raises:
        AssertionError: If any validation assertion fails.
    """
    print("\n--- Running Validator Script: Checking Data Integrity ---")
    
    # Assertion 1: Check if all entries possess required keys
    required_keys = ['id', 'original_text', 'risk_score', 'moderation_status']
    
    try:
        print("  [Assertion 1] Checking for required keys...")
        for i, entry in enumerate(processed_data):
            for key in required_keys:
                assert key in entry, f"Validation Failed: Entry {i} is missing key '{key}'."
        print("  [Assertion 1] Passed: All entries possess the correct keys.")
    except AssertionError as e:
        print(f"  [Validation FAILED] Structural Error: {e}")
        raise

    # Assertion 2: Check for at least one 'BLOCK' status
    print("  [Assertion 2] Checking for at least one 'BLOCK' entry...")
    block_found = any(entry.get('moderation_status') == 'BLOCK' for entry in processed_data)
    assert block_found, "Validation Failed: The pipeline did not generate any 'BLOCK' (High Risk) content."
    print("  [Assertion 2] Passed: Found at least one 'BLOCK' entry.")

    # Assertion 3: Check for at least one 'PASS' status
    print("  [Assertion 3] Checking for at least one 'PASS' entry...")
    pass_found = any(entry.get('moderation_status') == 'PASS' for entry in processed_data)
    assert pass_found, "Validation Failed: The pipeline did not generate any 'PASS' (Safe) content."
    print("  [Assertion 3] Passed: Found at least one 'PASS' entry.")
    
    print("\n===========================================================")
    print("✅ VALIDATION SUCCESS: All assertions passed. The pipeline output is validated.")
    print("===========================================================")


if __name__ == '__main__':
    # Example usage placeholder - normally this would accept data from another function
    print("--- Running validator.py (Self-Test Placeholder) ---")
    # To test this, you would need to pass a sample processed_data list here.
    pass